name: login
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.11
  google_sign_in: ^6.2.2
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^28.2.4+1
  url_launcher: ^6.3.1
  google_generative_ai: ^0.4.6
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.jpg
  adaptive_icon_foreground: assets/1024.png  
  adaptive_icon_background: "#ffffff"       


flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/google_logo.png